# PinMicro-style clones are often closer to nice!nano v1 than v2.
# In particular, the ZMK v1/v2 board revisions differ in EXT_POWER polarity.
---
include:
  - board: nice_nano@1//zmk
    shield: corne_left
  - board: nice_nano@1//zmk
    shield: corne_right
